config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get     'help'        => 'static_pages#help'
  get     'about'       => 'static_pages#about'
  get     'contact'     => 'static_pages#contact'

  get     'signup'      => 'users#new'
  get     'login'       => 'sessions#new'
  post    'login'       => 'sessions#create'
  delete  'logout'      => 'sessions#destroy'

  resources :users do
    member do
      get 'teacher_tool'
    end
  end
    resources :account_activations,   only: [:edit]
    resources :password_resets,       only: [:new, :create, :edit, :update]

    resources :rosters, only: [:create, :show, :update, :destroy]
    resources :courses do
      resources :pupils
      resources :studies
    end
      resources :teacher_invites, only: [:edit]

  resources :decks do
    member do
      get 'dynamic_list'
      get 'static_list'
      get 'learn_analaysis'
      get 'print'
      get 'repitition_alerts'
      get 'print_custom'
    end

    resources :cards do
      member do
        patch 'skill_update'
        get 'show_next'
        get 'show_previous'
        get 'static_show'
      end
      resources :trackers do
        member do
          get 'see_hint' # need to change to post?
          get 'see_backside'
        end
      end
    end
    resources :prints, only: [:new, :create, :fake]
    resources :reminders
  end

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many 				:decks
	has_many				:teacher_invites

	attr_accessor 	:remember_token, :activation_token, :reset_token

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

	before_save 		:downcase_email
	before_create 	:create_activation_digest

	validates 			:name, presence: true, length: { maximum: 50 }
	validates				:email, presence: true, length: { maximum: 255 },
													format: { with: VALID_EMAIL_REGEX },
													uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, length: { minimum: 6 }, allow_blank: true # this allows for updates to require password change.

	#Returns the hash digest of the given string.
	# This is for fixtures to use so we can 'see' the password and pass it in 'unhashed' to get it back hashed.
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
																									BCrypt::Engine::cost
		BCrypt::Password.create(string, cost: cost)
	end

	# Returns a random token.
	def User.new_token
		SecureRandom.urlsafe_base64
	end

	# Remember a user in the DB for use in persistent sessions.
	def remember
		self.remember_token = User.new_token #remember_token is set by attr_accessor!
		update_attribute(:remember_digest, User.digest(remember_token)) # this digests the remember token, then add's it to the DB column remmber_digest
	end

	# Forget a user. (We try to break cookies functionality here)
	def forget
		update_attribute(:remember_digest, nil)
	end

	# Returns true if given token matches the digest
	def authenticated?(attribute, token)
		digest = send("#{attribute}_digest")
		return false if digest.nil? # if multiple browser used, one log's out, force all browsers to logout.
		BCrypt::Password.new(digest).is_password?(token)
	end

	def activate
		update_columns(activated: true, activated_at: Time.zone.now )
		#update_attribute(:activated, true)
		#update_attribute(:activated_at, Time.zone.now)
	end

	def send_activation_email
		UserMailer.account_activation(self).deliver_now
	end

	# Sets the apssword reset attributes
	def create_reset_digest
		self.reset_token = User.new_token
		update_columns( reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now )
#		update_attribute(:reset_digest, User.digest(reset_token) )
#		update_attribute(:reset_sent_at, Time.zone.now )
	end

	# Sends password reset email
	def send_password_reset_email
		UserMailer.password_reset(self).deliver_now
	end

	# Returns true if a password reset has expired.
	def password_reset_expired?
		reset_sent_at < 2.hours.ago
	end

	private

		# Converts email to all lower-case
		def downcase_email
			self.email = email.downcase
		end

		# Create and assigns the activation token & digest
		def create_activation_digest
			self.activation_token  = User.new_token
			self.activation_digest = User.digest(activation_token)
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:index, :show, :edit, :update]
  before_action :correct_user, only: [:edit, :update]
  #before_action :delete_access, only: :destroy # this needs to work!!!
  #before_action :admin_user, only: :destroy

  def index
  #  @users = User.all
    if current_user.admin
      @users = User.paginate(page: params[:page], per_page: 50)
    else
      @users = User.where(shared: true).where(activated: true).paginate(page: params[:page], per_page: 30)
    end
  end

  def show
    @user = User.find(params[:id])
    @decks = Deck.where(user_id: @user.id)
    @deck = Deck.new
    if current_user?(@user) || current_user.admin? || @user.shared? # check if user is 'current user', admin or is publicly shared?
    else
       flash[:danger] = 'Not publicly accessible user. User must set public to true in Account Settings.'
       redirect_to(root_url)
     end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User account deleted."
    redirect_to users_url
  end

  def teacher_tool
    @teacher = User.find(params[:id])
    unless current_user.user_type == 'teacher'
      redirect_to @teacher
    end
    @rosters = Roster.where(teacher_id: @teacher.id)
    @courses = Course.where(teacher_id: @teacher.id)
    @decks = Deck.where(user_id: @teacher.id)
    @roster = Roster.new
    @course = Course.new
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :shared)
    end

    # Before filters

    # Confirm a logged-in user. THIS HAS BEEN MOVED TO APPLICATIONCONTROLLER
    # def logged_in_user
    #   unless logged_in?
    #     store_location
    #     flash[:danger] = "Please log in."
    #     redirect_to login_url
    #   end
    # end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    def delete_access
      unless correct_user || current_user.admin?
        flash[:danger] = "You're not authorized to delete this account."
        reidrect_to(root_url)
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<li>
	<% if current_user.admin %>
		<%= link_to user.name, user_path(user) %>
		<%= link_to "delete user", user, method: :delete, data: { confirm: "Are you sure?" } %>
	<% else %>
		<% if user.shared %>
			<%= link_to user.name, user_path(user) %>
		<% end %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit Account Settings") %>
<h1>Update your profile</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object  %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.label :shared, class: "checkbox inline" do %>
				<%= f.check_box :shared %>
				<span>Make account <strong>public</strong></span>
			<% end %>


			<%= f.submit "Save changes", class: 'btn btn-primary' %>
		<% end %>

	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<h1>All users</h1>

<%= will_paginate %>
	<ul class="users">

		<%= render @users %>

	</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign up</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.label :shared, class: "checkbox inline" do %>
				<%= f.check_box :shared %>
				<span>Make account <strong>public</strong></span>
			<% end %>



			<%= f.submit "Create my account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
	<div class="row">
		<div class="col-md-12">
			<h2><%= "#{@user.name}, email: #{@user.email}." %></h2>
		</div>
	</div>

	<% if current_user?(@user) %>
	<div class="row">
		<div class="col-md-8"<p><%= "#{@user.name}, you currently have #{@decks.count} deck." %>

		<ul>
			<% @decks.each do |deck| %>
				<li><%= link_to "#{deck.name}", deck_path(deck) %></li>
			<% end %>
		</ul>
		<p>Your public status is currently set to <strong><%= @user.shared ? 'public' : 'private' %></strong>.</p>
		<p><%= link_to 'delete my account', @user, method: :delete, data: { confirm: "Are you sure? This can not be undone." } %></p>

	</div>

	<div class="col-md-4">

		<% if @user.user_type == 'teacher' %>
		<%= link_to 'Teachers management tools', teacher_tool_user_path(@user) %>
		<% end %>
		<hr />


		<p>create a new deck:</p>
		<%= form_for @deck do |f| %>
		<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :description %>
			<%= f.text_area :description, class: 'form-control' %>

			<% if current_user.admin %>
				<%= f.label :tracked, class: "checkbox inline" do %>
					<%= f.check_box :tracked %>
					<span>Track my progress</span>
				<% end %>
			<% end %>


			<%= f.submit "Create Deck" %>
			<% end %>
	</div>
</div>



	<% end %>

app/views/users/teacher_tool.html.erb
<h3>This is <%= @teacher.name %>'s Teacher Management tool.</h3>
<p>
	<h4>Student Roster</h4><br />
	This gives you access to create a roster of students, from which you can add to your courses:<br />
	You currently have <%= pluralize @rosters.count, "student" %> in your roster<br />



	<%= form_for(@roster, remote: true) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>

	<%= f.label :roster_invite_email, "email:" %>
	<%= f.text_field :roster_invite_email %>
	<br />
	<%= f.label :name, 'If name matches before @ symbol in email, leave below field blank.' %>
	<%= f.text_field :name %>
	<%= f.submit 'send invitation' %>
	<% end %>
	Full list of roster of students:<br />
	<ul>
	<% @rosters.each do |student| %>
	<li><%= link_to User.find_by(id: student.student_id).name, roster_path(student) %></li>
	<% end %>
	</ul>
</p>

<p>
	<hr />
	<h4>Courses</h4>
	Access your current courses here:<br />
	<%= link_to 'create new course', new_course_path %><br />
	or manage your previously <%= "#{@courses.count} " %> created courses:<br />
	<ul>
	<% @courses.each do |course| %>
		<li><%= link_to "#{course.title}", course_path(course) %></li>
	<% end %>
</ul>
</p>