config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get     'help'        => 'static_pages#help'
  get     'about'       => 'static_pages#about'
  get     'contact'     => 'static_pages#contact'

  get     'signup'      => 'users#new'
  get     'login'       => 'sessions#new'
  post    'login'       => 'sessions#create'
  delete  'logout'      => 'sessions#destroy'

  resources :users do
    member do
      get 'teacher_tool'
    end
  end
    resources :account_activations,   only: [:edit]
    resources :password_resets,       only: [:new, :create, :edit, :update]

    resources :rosters, only: [:create, :show, :update, :destroy]
    resources :courses do
      resources :pupils
      resources :studies
    end
      resources :teacher_invites, only: [:edit]

  resources :decks do
    member do
      get 'dynamic_list'
      get 'static_list'
      get 'learn_analaysis'
      get 'print'
      get 'repitition_alerts'
      get 'print_custom'
    end

    resources :cards do
      member do
        patch 'skill_update'
        get 'show_next'
        get 'show_previous'
        get 'static_show'
      end
      resources :trackers do
        member do
          get 'see_hint' # need to change to post?
          get 'see_backside'
        end
      end
    end
    resources :prints, only: [:new, :create, :fake]
    resources :reminders
  end

end

app/views/shared/_bottom_nav.html.erb
<div class='navbar navbar-fixed-bottom navbar-inverse'>
	<div class="container">
		<div class='navbar-header'>
		<ul class='nav navbar-nav navbar-left'>
			<li><%= link_to 'About', about_path %></li>
			<li><%= link_to 'Help', help_path %></li>
			<li><%= link_to 'Contact', contact_path %></li>
		</ul>
	</div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_top_nav.html.erb
<header class="navbar navbar-static-top navbar-inverse">
	<div class="container">
		<div class="navbar-left">
			<%= link_to image_tag("navbar_logo.png", id: "nav_logo") %> <%= link_to 'Lethe', root_path, id: 'nav_brand_name' %>
		</div>
		<nav>
			<ul class='nav navbar-nav navbar-right' id='topNavAlteration'>
					<% if logged_in? %>

						<li><%= link_to 'Log out', logout_path, method: 'delete' %></li>
						<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><%= link_to 'Profile', current_user %></li>
								<li><%= link_to "Settings", edit_user_path(current_user) %></li>
								<li class="divider"></li>
								<li><a href="#">Deck list here</a></li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to 'Log in', login_path %></li>
						<li><%= link_to 'Sign up', signup_path %></li>
					<% end %>
				<li><%= link_to 'Home', root_path %></li>
				<% if logged_in? %>
					<li><%= link_to "All users", users_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/shared/no_visual_feedback.js.erb
console.log("No visual feedback js executed.");