config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get     'help'        => 'static_pages#help'
  get     'about'       => 'static_pages#about'
  get     'contact'     => 'static_pages#contact'

  get     'signup'      => 'users#new'
  get     'login'       => 'sessions#new'
  post    'login'       => 'sessions#create'
  delete  'logout'      => 'sessions#destroy'

  resources :users do
    member do
      get 'teacher_tool'
    end
  end
    resources :account_activations,   only: [:edit]
    resources :password_resets,       only: [:new, :create, :edit, :update]

    resources :rosters, only: [:create, :show, :update, :destroy]
    resources :courses do
      resources :pupils
      resources :studies
    end
      resources :teacher_invites, only: [:edit]

  resources :decks do
    member do
      get 'dynamic_list'
      get 'static_list'
      get 'learn_analaysis'
      get 'print'
      get 'repitition_alerts'
      get 'print_custom'
    end

    resources :cards do
      member do
        patch 'skill_update'
        get 'show_next'
        get 'show_previous'
        get 'static_show'
      end
      resources :trackers do
        member do
          get 'see_hint' # need to change to post?
          get 'see_backside'
        end
      end
    end
    resources :prints, only: [:new, :create, :fake]
    resources :reminders
  end

end

app/models/card.rb
class Card < ActiveRecord::Base
	belongs_to :deck
	has_one :tracker, dependent: :destroy

	accepts_nested_attributes_for :tracker

	mount_uploader :picture, PictureUploader

	default_scope { order('created_at ASC') }

	validate :picture_size

	private
		# Validates the size of an uploaded picture
		def picture_size
			if picture.size > 500.kilobytes
				errors.add(:picture, "should be less than 500kB")
			end
		end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

	def show
		#1st you retrieve the post thanks to params[:post_id]
		deck = Deck.find(params[:deck_id])
		#2nd you retrieve the comment thanks to params[:id]
		@card = deck.cards.find(params[:id])
#		@tracker = Tracker.new --This should be created already. Test and cofirm to remove.
		@current_collection_arr = Card.where(deck_id: deck) # who needs this? Test and cofirm to remove.
	end

	def create
		deck = Deck.find(params[:deck_id])
		@card = deck.cards.create(card_params)
		if @card.save
			if deck.tracked
				Tracker.create!(card_id: @card.id)
			end
			flash[:success] = "New card was created."
			redirect_to deck_path(deck)
		else
			flash[:danger] = "Deck was not created"
			redirect_to deck_path(@card.deck_id)
		end
	end

	def edit
		@card = Card.find(params[:id])
	end

	def update
		@card = Card.find(params[:id])
		if @card.deck.tracked
			detect_changes
		end
		if @card.update_attributes(card_params)
			if @card.deck.tracked
				prop_changed?
			end
			flash[:success] = "Card info updated."
			respond_to do |format|
				format.html { render 'show' }
			end
		else
			render 'edit'
		end
	end

	def destroy
		deck = Deck.find(params[:deck_id])
		@card = Card.find(params[:id]).destroy
		flash[:success] = "Card has been deleted."
		redirect_to deck_path(deck)
		#redirect_to current_user
	end

	def skill_update # remove to tracker_cotroller.rb? Test and cofirm to remove.
		@card = Card.find(params[:id])
		if @card.update_attributes(card_params)
			tracker = Tracker.find_by(card_id: @card.id)
			levelChange = tracker.level_changed.push([Time.zone.now, @card.level])
			tracker.update_attribute(:level_changed, levelChange)
			# respond_to do |format|
			# 	format.js { render 'shared/no_visual_feedback'}
			# end
			respond_to do |format|
				format.js
			end
		end
#		flash[:danger] = "Update of skill level didn't save."
#		render 'show'
	end

	def show_next
		list_arr = cookies.permanent[:cards_list].split(',')
		list_arr.rotate!(1)
		cookies.permanent[:cards_list] = (list_arr.class == Array) ? list_arr.join(',') : ''
		deck = Deck.find(params[:deck_id])
		redirect_to deck_card_path(deck, list_arr[0])
	end

	def show_previous
		list_arr = cookies.permanent[:cards_list].split(',')
		list_arr.rotate!(-1)
		cookies.permanent[:cards_list] = (list_arr.class == Array) ? list_arr.join(',') : ''
		deck = Deck.find(params[:deck_id])
		redirect_to deck_card_path(deck, list_arr[0])
	end

	def static_show
		# this is only used if clicked on from deck/show page w/out choosing a static or random list option.
		@deck = Deck.find(params[:deck_id])
		list_arr = Card.where(deck_id: @deck.id).ids
		this_card = Card.find(params[:id]).id
		position = list_arr.index(this_card)
		list_arr.rotate!(position)
		# this exists in deck controller. Maybe move to application_controller?
		cookies.permanent[:cards_list] = (list_arr.class == Array) ? list_arr.join(',') : '' # pushes user.id into user_id; encrypts user_id, adds 20 years to it, then bakes a cookie out of it.
		redirect_to deck_card_path(@deck, list_arr[0])
	end

	private

	def card_params
		params.require(:card).permit(:front, :hint, :level, :back, :deck_id, :picture)
	end

	def detect_changes
		@changed = []
		@changed << :front if @card.front != params[:card][:front]
		@changed << :hint if @card.hint != params[:card][:hint]
		@changed << :back if @card.back != params[:card][:back]
	end

	def prop_changed?
		@changed.each do |check|
			@changed.include? check
			puts "Following attribute was changed : #{check}"
			update_tracker(check)
		end
	end

	def update_tracker(card_attribute)
		tracker_attribute =  case card_attribute
		when :front; :front_changed
		when :back; :back_changed
		when :hint; :hint_changed
		end
		string_tracker_column = tracker_attribute.to_s
		@tracker ||= Tracker.find_by(card_id: @card.id)
		update_array = @tracker[tracker_attribute]
		puts "update_array is #{update_array}"
		# if update_array.length == 0 # if update_array is [[]], fix:
		# 	update_array = []
		# 	puts "---------------   update_array was set to []   ---------------"
		# end

		puts "did update_array get correct content? #{update_array}"
		update_array << [Time.zone.now, @card[card_attribute]]
		puts "last info to push into array is #{update_array[-1]}"
		puts "full data array looks like this : #{update_array}"
		@tracker.update_attribute(tracker_attribute, update_array)
		#tracker.update_attribute(:hint_used_arr, hintTime)
	end

end

app/helpers/cards_helper.rb
module CardsHelper

	def tracker_was_exposed(cards_id)
		@tracker = Tracker.find_by(card_id: cards_id)
		exposureTime = @tracker.exposure_arr.push(Time.zone.now)
		@tracker.update_attribute(:exposure_arr, exposureTime)
	end

	def get_tracker
		return @tracker
	end

	def get_card_from_list(alteration = 0)
		puts ("What the heck does this spit out?")
		puts (cookies.permanent[:cards_list])
		list_arr = cookies.permanent[:cards_list].split(',')
		temp_ref = list_arr.rotate(alteration)
		#cookies.permanent[:cards_list] = (list_arr.class == Array) ? list_arr.join(',') : ''
		return temp_ref[0]
	end

	def get_card_arr_position(alteration = 0)
		cards_list = Card.where(deck_id: @card.deck).ids
		# get current show id:
		current_position = cards_list.index(@card.id)
		wanted_position = current_position + alteration
		if wanted_position == cards_list.length
			wanted_position = 0
		end

		cards_list[wanted_position]
	end

	def create_smart_randomlist
	 	id_level_array = Card.where(deck_id: @card.deck).pluck(:id, :level)
		@learn_list = [] # clear list if existing.
		expose_card_level_multiplication(id_level_array)
		id_level_array.each do |item|
			@learn_list.fill(item[0], @learn_list.size, item[1])
		end
		@learn_list.shuffle! # figure out this? http://stackoverflow.com/questions/19261061/picking-a-random-option-where-each-option-has-a-different-probability-of-being
		@learn_list = no_double_exposures(@learn_list)
		return @learn_list
	end

	def create_static_list
		@learn_list = Card.where(deck_id: @card.deck).ids
	end

	# change exposure levels to your needs.
	def expose_card_level_multiplication(nested_array)
		nested_array.each { |id_level|
				id_level[1] = case id_level[1]
					when 1
						12
					when 2
						8
					when 3
						4
					when 4
						2
					when 5
						1
					end
		}
		return nested_array
	end

	def no_double_exposures(shuffled_arr)
		newArr = []
		# make sure first & last are not the same.
		if(shuffled_arr[0] == shuffled_arr[-1])
			shuffled_arr.pop
		end
		#shuffled_arr.each_cons(2).map{ |a,b| if a == b ? shuffled_arr.delete(b) }
		# shuffled_arr.each_cons(2).map do |a,b|
		# 	if a == b
		# 		puts "#{a} = #{b}"
		# 		shuffled_arr.delete_at(b)
		# 	end
		# end
		#[0,*shuffled_arr].each_cons(2).map {|x,y| y - x }

		previous = nil
	 	for count in shuffled_arr
			#puts "Fresh count is: #{count} & #{previous}"
		 	if previous.nil?
			#	puts "nil was true the first time"
		 		previous = count
				newArr.push(count)
		 		next
			elsif previous != count
			#	puts "ADDING: #{previous} vs #{count}"
				newArr.push(count)
				previous = count
			else
			#	puts "NOT adding: #{previous} vs #{count}"
			end
		#puts "previous changed to #{previous}"
		#puts ""
		end
		return newArr
	end

end

app/views/cards/_show.html.erb
The non tracker page.
<% if @card.hint != "" || nil %>
	<div>
		<button id="reveal_hint_button">show hint</button><span id="hint_text"><%= @card.hint %></span>
	</div>
<% end %>
<div>
	<button id="reveal_card_button">show card</button><p id="backside_text"><%= @card.back %>
	<%= image_tag @card.picture.url if @card.picture? %></p>
</div>
<div>
<p><%= link_to 'update card', edit_deck_card_path(@card.deck_id, @card) %></p>
<p><%= link_to 'delete this card', [@card.deck, @card], method: :delete, data: { confirm: "Are you sure? This can not be undone." } %></p>

<div id="show_self_evaluation">
	<%= form_for [@card.deck, @card], remote: true, html: { class: "show_skillUpdate, form-inline" } do |f| %>
		<%= f.label :level, 'knowledge level: ' %>
			<%= f.radio_button :level, 1 %><%= f.label 1, "Unknown" %>

			<%= f.radio_button :level, 2 %><%= f.label 2, "Vague" %>

			<%= f.radio_button :level, 3 %><%= f.label 3, "Known" %>

			<%= f.radio_button :level, 4 %><%= f.label 4, "Confident" %>

			<%= f.radio_button :level, 5 %><%= f.label 5, "Mastered" %>
	<%= f.submit "Update Card", id: "radioButtonsSubmit", style: "display: none;" %>
	<% end %>

</div>

app/views/cards/_tracker_show.html.erb
This card is being <strong>tracked</strong>.
<% tracker_was_exposed(@card.id) %>
<% if @card.hint != "" || nil %>
	<div>
		<%= link_to "Reveal Hint", see_hint_deck_card_tracker_path(@card.deck, @card, get_tracker), id: "reveal_hint_button", remote: true  %>
		<span id="hint_text"><%= @card.hint %></span>
	</div>
<% end %>
<div>
	<%= link_to "Show Card", see_backside_deck_card_tracker_path(@card.deck, @card, get_tracker), id: "reveal_card_button", remote: true  %>
	<p id="backside_text">
		<%= @card.back %>
		<%= image_tag @card.picture.url if @card.picture? %>
	</p>
</div>
<div>
<p><%= link_to 'update card', edit_deck_card_path(@card.deck_id, @card) %></p>

<p><%= link_to 'delete this card', [@card.deck, @card], method: :delete, data: { confirm: "Are you sure? This can not be undone." } %></p>

<div id="show_self_evaluation">
	<%= form_for [@card.deck, @card], :url => skill_update_deck_card_path(@card.deck, @card), remote: true do |f| %>
		<%= f.label :level, 'knowledge level: ' %>
			<%= f.radio_button :level, 1 %><%= f.label 1, "Unknown" %>
			<%= f.radio_button :level, 2 %><%= f.label 2, "Vague" %>
			<%= f.radio_button :level, 3 %><%= f.label 3, "Known" %>
			<%= f.radio_button :level, 4 %><%= f.label 4, "Confident" %>
			<%= f.radio_button :level, 5 %><%= f.label 5, "Mastered" %>
	<%= f.submit "Update Card", id: "radioButtonsSubmit", style: "display: none;" %>
	<% end %>
</div>
<div id="tracker_container">
<%= link_to 'see tracker data', deck_card_tracker_path(@card.deck, @card, get_tracker), remote: true, id: 'show_tracker'%>
</div>

app/views/cards/edit.html.erb
<%= @card.front %>
Edit card here.
<%= form_for [@card.deck, @card] do |f| %>
	<%= render 'shared/error_messages', object: f.object  %>

	<%= f.label :front %>
	<%= f.text_field :front, class: 'form-control' %>

	<%= f.label :hint %>
	<%= f.text_field :hint, class: 'form-control' %>

	<% if false %>
		<% learning_level = options_for_select([ ["unknown", 1], ["vague", 2], ["known", 3], ["confident", 4], ["mastered", 5] ], selected: @card.level) %>
		<%= f.label :level, 'knowledge level: ' %>
		<%= f.select :level, learning_level %>
	<% end %>
	
	<%= f.label :back %>
	<%= f.text_area :back, class: 'form-control' %>

	<%= f.submit "Update Card" %>
<% end %>

app/views/cards/show.html.erb
<% provide(:title, @card.front) %>
<%= link_to @card.deck.name, @card.deck %>
<p><%= link_to 'previous card', show_previous_deck_card_path(@card.deck, get_card_from_list(-1)) %>
	 ||
	<%= link_to 'next card', show_next_deck_card_path(@card.deck, get_card_from_list(1)) %></p>
<h1><%= @card.front %></h1>
<% if @card.deck.tracked %>
 	<%= render 'tracker_show' %>
<% else %>
 	<%= render 'show' %>
<% end %>

app/views/cards/skill_update.js.erb
console.log("Update of skill written to Card. Maybe figure out how to from here recall the shuffle if being used?");