config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get     'help'        => 'static_pages#help'
  get     'about'       => 'static_pages#about'
  get     'contact'     => 'static_pages#contact'

  get     'signup'      => 'users#new'
  get     'login'       => 'sessions#new'
  post    'login'       => 'sessions#create'
  delete  'logout'      => 'sessions#destroy'

  resources :users do
    member do
      get 'teacher_tool'
    end
  end
    resources :account_activations,   only: [:edit]
    resources :password_resets,       only: [:new, :create, :edit, :update]

    resources :rosters, only: [:create, :show, :update, :destroy]
    resources :courses do
      resources :pupils
      resources :studies
    end
      resources :teacher_invites, only: [:edit]

  resources :decks do
    member do
      get 'dynamic_list'
      get 'static_list'
      get 'learn_analaysis'
      get 'print'
      get 'repitition_alerts'
      get 'print_custom'
    end

    resources :cards do
      member do
        patch 'skill_update'
        get 'show_next'
        get 'show_previous'
        get 'static_show'
      end
      resources :trackers do
        member do
          get 'see_hint' # need to change to post?
          get 'see_backside'
        end
      end
    end
    resources :prints, only: [:new, :create, :fake]
    resources :reminders
  end

end

app/models/deck.rb
class Deck < ActiveRecord::Base

	belongs_to 		:user
	has_many 			:cards, dependent: :destroy
	has_one				:reminder, dependent: :destroy

	validates			:name, presence: true, length: { minimum: 1 }
	validates			:user_id, presence: true

	def create_smart_randomlist
		id_level_array = Card.where(deck_id: self.id).pluck(:id, :level)
		#id_level_array = Card.where(deck_id: @card.deck).pluck(:id, :level)
		@learn_list = [] # clear list if existing.
		expose_card_level_multiplication(id_level_array)
		id_level_array.each do |item|
			@learn_list.fill(item[0], @learn_list.size, item[1])
		end
		@learn_list.shuffle! # figure out this? http://stackoverflow.com/questions/19261061/picking-a-random-option-where-each-option-has-a-different-probability-of-being
		@learn_list = no_double_exposures(@learn_list)
		return @learn_list
	end

	def deck_create_static_list
		@learn_list = Card.where(deck_id: self.id).ids
		return @learn_list
	end

	def next_card_from_list(direction = 0)
		return @learn_list.rotate!(direction)
	end

	# def create_cookie_cards_list(list_arr)
	# 	cookies.permanent[:cards_list] = (list_arr.class == Array) ? list_arr.join(',') : '' # pushes user.id into user_id; encrypts user_id, adds 20 years to it, then bakes a cookie out of it.
	# end

	# def create_pdf
	# end


	private

		# change exposure levels to your needs.
		def expose_card_level_multiplication(nested_array)
				nested_array.each { |id_level|
						id_level[1] = case id_level[1]
							when 1
								12
							when 2
								8
							when 3
								4
							when 4
								2
							when 5
								1
							end
				}
				return nested_array
			end

			def no_double_exposures(shuffled_arr)
				newArr = []
				# make sure first & last are not the same.
				if(shuffled_arr[0] == shuffled_arr[-1])
					shuffled_arr.pop
				end
				previous = nil
				for count in shuffled_arr
					#puts "Fresh count is: #{count} & #{previous}"
					if previous.nil?
					#	puts "nil was true the first time"
						previous = count
						newArr.push(count)
						next
					elsif previous != count
					#	puts "ADDING: #{previous} vs #{count}"
						newArr.push(count)
						previous = count
					else
					#	puts "NOT adding: #{previous} vs #{count}"
					end
				#puts "previous changed to #{previous}"
				#puts ""
				end
				return newArr
			end


end

app/controllers/decks_controller.rb
class DecksController < ApplicationController

	def show
		@deck = Deck.find(params[:id])
		@cards = Card.where(deck_id: @deck.id)
		@card = Card.new
		cards_list = @deck.deck_create_static_list
		create_cookie_cards_list(cards_list)
	end

	def create
		@deck = Deck.new(deck_params)
		@deck.user_id = current_user.id
		#byebug
		params[:deck][:tracked] == '1' ? @deck.tracked = true : @deck.tracked = false
		if @deck.save
			flash[:success] = "Deck was created"
			redirect_to user_path(current_user.id)
		else
			flash[:danger] = "Deck was not created"
			redirect_to user_path(current_user.id)
		end
	end

	def edit
		@deck = Deck.find(params[:id])
	end

	def update
		@deck = Deck.find(params[:id])
		if @deck.update_attributes(deck_params)
			flash[:success] = "Deck settings were updated."
			redirect_to deck_path(@deck)
		else
			render 'edit'
		end
	end

	def destroy
		Deck.find(params[:id]).destroy
		flash[:success] = "Deck and all cards belonging to it have been removed."
		redirect_to current_user
	end

	def dynamic_list
		@deck = Deck.find(params[:id])
		cards_list = @deck.create_smart_randomlist
		create_cookie_cards_list(cards_list)
		redirect_to deck_card_path(@deck, cards_list[0])
	end

	def static_list
		@deck = Deck.find(params[:id])
		cards_list = @deck.deck_create_static_list
		create_cookie_cards_list(cards_list)
		redirect_to deck_card_path(@deck, cards_list[0])
	end

	def learn_analaysis
		@deck = Deck.find(params[:id])
		@cards = Card.where(deck_id: @deck.id)
		@trackers = Tracker.where(card_id: @cards.ids)
	end

	def print
		@deck = Deck.find(params[:id])
		@card_ids = Card.where(deck_id: @deck.id).ids
	end

	def print_custom
		@deck = Deck.find(params[:id])
		@cards = Card.where(deck_id: @deck.id)
	end

	def repitition_alerts
		@deck = Deck.find(params[:id])
		if Reminder.exists?(deck_id: @deck.id).present?
			puts "----------------------------- CHECK IF REMINDER ALREADY EXIST? -----------------------------"
			@reminder = Reminder.find_by(deck_id: @deck.id)
			redirect_to deck_reminder_path(@deck, @reminder)
		else
			puts "----------------------------- CREATE NEW REMINDER -----------------------------"
			@reminder = Reminder.new
		end
	end

	private

	def deck_params
		params.require(:deck).permit(:name, :description, :user_id, :tracker)
	end

	def create_cookie_cards_list(list_arr)
		cookies.permanent[:cards_list] = (list_arr.class == Array) ? list_arr.join(',') : '' # pushes user.id into user_id; encrypts user_id, adds 20 years to it, then bakes a cookie out of it.
	end

end

app/helpers/decks_helper.rb
module DecksHelper



	def create_pdf(cards, size, card_per_page)
		
	end
	# def create_deck_list
	# 	@id_list = @cards.ids#.map(&:to_s)
	# 	#@id_list = @cards.pluck(:id)
	# end

	# def set_current_position(alteration = 0)
	# 	@id_list = @cards.ids
	# 	return @id_list[alteration]
	#
	# 	#return @id_list[@start_position]
	# end
	#
	# def deck_list
	# 	return @id_list
	# end


end

app/views/decks/_custom_select.html.erb
	<p><strong>Select cards to include:</strong></p>

<% @cards.each do |card| %>
<%= check_box_tag(card.id, card.id, false, :onclick=>"add_card_to_print_list(#{card.id});")%><%= "#{card.front}" %>
<% end %>
<br />
<a href="#"  id="add-card">pdf selected cards only - front.</a>

<!--onclick="add_card_to_print_list('test')" -->

app/views/decks/edit.html.erb
<% provide(:title, "Deck Settings") %>
<h1>Deck settings for <%= @deck.name %></h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@deck) do |f| %>
			<%= render 'shared/error_messages', object: f.object  %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :description %>
			<%= f.text_area :description, class: 'form-control' %>

			<%= f.submit "Save setting changes", class: 'btn btn-primary' %>
		<% end %>
		<p><%= link_to 'delete this deck', @deck, method: :delete, data: { confirm: "Are you sure? This can not be undone." } %></p>
	</div>
</div>

app/views/decks/learn_analaysis.html.erb
<% provide(:title, @deck.name) %>
back to <%= link_to @deck.name, deck_path(@deck) %> deck page
<p>The <strong><%= @deck.name %></strong> deck has totale of <%= @cards.count %> cards.</p>

<p>This is just a big overwhelming data dump.<br />
Will be designed differently in design phase.</p>
<ul>
<% @cards.each do |card| %>
  <li><%= card.front %> has been used <%= pluralize(card.tracker.exposure_arr.count, 'time') %>
		<ul>
			<li>
			<% if card.tracker.exposure_arr.count == card.tracker.hint_used_arr.count %>
				Hint was always used.
			<% else %>
				Hint was used <%= pluralize(card.tracker.hint_used_arr.count, 'time') %>.
			<% end %>
		</li>
		<li>
			<% if card.tracker.exposure_arr.count == card.tracker.back_exposure_arr.count %>
				Card was always used.
			<% else %>
				Card was used <%= pluralize(card.tracker.back_exposure_arr.count, 'time') %>.
			<% end %>
		</li>
		<li>Skill level was changed <%= pluralize(card.tracker.level_changed.count, 'time') %>.</li>
		<li>Front of card was changed <%= pluralize(card.tracker.front_changed.count, 'time') %>.</li>
		<li>Card itself was changed <%= pluralize(card.tracker.back_changed.count, 'time') %>.</li>
		<li>Hint was changed <%= pluralize(card.tracker.hint_changed.count, 'time') %>.</li>


		</ul>
	</li>
<% end %>
</ul>

app/views/decks/print.html.erb
This is the print page
<div>
<p><strong>PDF file</strong> for print. (This generates 2 pdf's: Front_side.pdf and Back_side.pdf.)</p>
<!-- <p><%= link_to 'test me', new_deck_print_path(@deck, @card_ids, type: 'pdf', paper_width: 6, paper_height: 4, cards_per_paper: 2), remote: true %></p> -->
<p><%= link_to 'Full deck, 2 cards on 6x4 inch paper - front side', new_deck_print_path(@deck, type: 'pdf', paper_width: 6, paper_height: 4, cards_per_paper: 2, side: 'front', format: "pdf") %></p>
<p><%= link_to 'Full deck, 2 cards on 6x4 inch paper - back side', new_deck_print_path(@deck, type: 'pdf', paper_width: 6, paper_height: 4, cards_per_paper: 2, side: 'back', format: "pdf") %></p>

<!-- <p><%= link_to 'Full deck, 2 cards on 6x4 inch paper', create_pdf([@card_ids], '6x4', 2 ), remote: true  %></p>
<p><%= link_to 'Full deck, 1 card on 6x4 inch paper', create_pdf([@card_ids], '6x4', 1 ), remote: true %></p>
<p><%= link_to 'Full deck, 6 cards on 8.5x11 inch paper', create_pdf([@card_ids], '8.5x11', 6 ), remote: true %></p>
<p><%= link_to 'Full deck, 6 cards on A4 paper', create_pdf([@card_ids], 'A4', 6 ), remote: true %></p>

</div>
<hr>
<div>

<p><strong>InDesign csv</strong> files. (See InDesign Templates and tutorial for importing)</p>
<p><%= link_to 'Full deck, 2 cards on 6x4 inch paper', '#' %></p>
<p><%= link_to 'Full deck, 1 card on 6x4 inch paper', '#' %></p>
<p><%= link_to 'Full deck, 6 cards on 8.5x11 inch paper', '#' %></p>
<p><%= link_to 'Full deck, 6 cards on A4 paper', '#' %></p>
<p>Benefits of using this is that you can edit the final InDesign file before printing, but you need to have InDesign.<br />
<p><%= link_to 'tutorial how to import CSV', '#' %></p>
<p><%= link_to 'InDesign template files', '#' %></p>
(Tested on InDesign 2015CC only.)</p> -->

</div>
<hr>
<%= link_to 'selected individual cards', print_custom_deck_path(@deck), id: "select_cards", remote: true %>
<div id="cards_container">
</div>
<%= link_to "red rum test", new_deck_print_path(@deck, custom_select_items: "", type: 'pdf', paper_width: 6, paper_height: 4, cards_per_paper: 2, side: 'front', format: "pdf"), id: "custom_cards" %>

app/views/decks/print_custom.js.erb
console.log('Add All cards as print options.');
$("#select_cards").remove();
$('div#cards_container').append(" <%= escape_javascript(render partial: 'custom_select') %> ");

$('#add-card').click(function(event) {
  event.preventDefault();
  $.post('/decks/'+ location.pathname.match(/^\/decks\/(\d+)/)[1] +'/prints',
  { contentType: 'pdf', cards: cards_for_printing, type: 'pdf', paper_width: 6, paper_height: 4, cards_per_paper: 2, side: 'front', format: 'pdf' })
    .done(function(result) {
      console.log(result);
    }
  );
});

app/views/decks/repitition_alerts.html.erb
<h3>Create reminders for deck <%= @deck.name %>:</h3>
<p>If you have mastered all cards you might want to use the Pimslur repition setup:</p>
<p>1 day, 5 days, 25 days, 4 months, 2 years. <strong>

	<%= link_to 'make alerts', deck_reminders_path(
	@deck,
	@reminder,
	{action: :create},
	reminder: {
		next_alert: (DateTime.now + 1.day),
		alerts: [ (DateTime.now + 5.days), (DateTime.now + 25.days), (DateTime.now + 4.months), (DateTime.now + 2.years) ],
		repeating: false
	}
	), method: :post %>
</strong></p>


</p>
<hr />
<p>Or if you haven't mastered all the cards in the deck and just want to get a once only or repeated reminder:<br />

	<ul>
		<li><%= form_for [@deck, @reminder] do |f| %>
				<%= render 'shared/error_messages', object: f.object  %>
				<%= f.label :day_count, 'how many alerts:' %>
				<%= f.number_field :day_count, class: 'form-control' %>
				<%= f.label :interval, 'with how many days between each alert:' %>
				<%= f.number_field :interval, class: 'form-control' %>
				<%= f.submit "Create Daily alerts" %>
			<% end %></li>
			<li><%= form_for [@deck, @reminder] do |f| %>
					<%= render 'shared/error_messages', object: f.object  %>
					<%= f.label :week_count, 'how many alerts:' %>
					<%= f.number_field :week_count, class: 'form-control' %>
					<%= f.label :interval, 'with how many weeks between each alert:' %>
					<%= f.number_field :interval, class: 'form-control' %>
					<%= f.submit "Create Weekly alerts" %>
				<% end %></li>
	</ul>
</p>

Read more about this specific setup and spaced repition techniques <a href='http://mt.artofmemory.com/wiki/Spaced_Repetition_and_Recall'>here</a>.

app/views/decks/show.html.erb
<% provide(:title, @deck.name) %>
	<div class="row">
		<div class="col-md-12">
			<h2><%= @deck.name %></h2>
		</div>
	</div>

	<div class="row">
		<div class="col-md-8">
			<p><%= @deck.description %></p>
			<p><%= link_to 'Print cards', print_deck_path(@deck) %></p>

			<%= link_to 'Setup practive reminders', repitition_alerts_deck_path(@deck) %></p>
			<p>Card rehersal options:<br />
			<ul>
				<li><%= link_to "All equal", static_list_deck_path, title: "Runs through card exactly as sequence of below listed." %></li>
				<li><%= link_to "Random lower skill", dynamic_list_deck_path, title: "Random list, but skewed towards lower ranked skill levels." %></li>
			</ul>
			</p>
			<p><%= "#{@deck.name}, has currently #{@cards.count} cards in it." %></p>


		<ul>
			<% @cards.each do |card| %>
				<li><%= link_to "#{card.front}", static_show_deck_card_path(@deck, card) %></li>
			<% end %>
		</ul>
		<p><%= link_to 'Deck settings', edit_deck_path %>

		<% if @deck.tracked %>
			<p><%= link_to 'View All Tracker data', learn_analaysis_deck_path(@deck) %></p>
		<% end %>



	</div>
	<div class="col-md-4">

		<%= form_for [@deck, @card], html: { multipart: true } do |f| %>
				<%= render 'shared/error_messages', object: f.object  %>

			<%= f.label :front %>
			<%= f.text_field :front, class: 'form-control' %>

			<%= f.label :hint %>
			<%= f.text_field :hint, class: 'form-control' %>

			<% learning_level = options_for_select([ ["unknown", 1], ["vague", 2], ["known", 3], ["confident", 4], ["mastered", 5] ], selected: @card.level) %>
			<%= f.label :level, 'knowledge level: ' %>
			<%= f.select :level, learning_level %>

			<%= f.label :back %>
			<%= f.text_area :back, class: 'form-control' %>

			<%= f.submit "Create Card" %>
			<% if current_user.admin %>
			<span class="picture"><%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %></span>
			<% end %>
		<% end %>

		<!-- this is only for user understanding. The limit is enforced on server end as well -->
		<script type="text/javascript">
		  $('#card_picture').bind('change', function() {
		    var size_in_kilobytes = this.files[0].size/1024;
		    if (size_in_kilobytes > 500) {
		      alert('Maximum file size is 500kB. Please choose a smaller file.');
		    }
		  });
		</script>
	</div>
</div>